###服务端口号
server:
  port: 8202
spring:
  application:
    name: consul-consumer
  ####consul注册中心地址
  cloud:
    consul:
      host: 10.0.41.20
      port: 8500
      discovery:
        hostname: 10.0.41.170
