###服务端口号
server:
  port: 8701

###服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka

spring:
  application:
    ####注册中心应用名称
    name: config-server
  cloud:
    config:
      server:
        git:
          ###git环境地址
          uri: https://github.com/dailiangaini/SpringCloudConfig.git
          ####搜索目录
          search-paths: config
      ####读取分支
      label: master

## 访问地址：http://127.0.0.1:8701/cloud-config-dev.yml
## http://127.0.0.1:8701/cloud-config/dev