###注册 中心
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8100/eureka/
server:
  port: 8901

spring:
  application:
    name: gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true

      default-filters:
        ## 设置需要替换第几个/
        ## /**   0
        ## /act/**   1
        ## /api/act/**   2
        - StripPrefix=0
      routes:
        - predicates:
            - Path=/**
          uri: lb://eureka-provider
          id: eureka-provider-route

#        -
management:
  endpoints:
    web:
      exposure:
        include: gateway

